directories:
  output: build
  buildResources: build
productName: 犇鸟视频
appId: hk.collinschina.com
files:
  - filter:
      - dist/electron/**/*
dmg:
  contents:
    - x: 410
      'y': 150
      type: link
      path: /Applications
    - x: 130
      'y': 150
      type: file
mac:
  icon: build/icons/icon.icns
win:
  target:
    - nsis
  icon: build/icons/icon.ico
nsis:
  oneClick: false
  deleteAppDataOnUninstall: true
  allowToChangeInstallationDirectory: true
electronVersion: 2.0.18
